server:
  port: 8081

spring:
  application:
    name: account-service

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        type:
          json_format_mapper: com.pitisha.project.mybank.accountservice.domain.entity.mapper.CustomJsonFormatMapper

  liquibase:
    enabled: true
    contexts: dev

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}

  cloud:
    vault:
      uri: http://localhost:8200
      authentication: APPROLE
      app-role:
        role-id: ${VAULT_ROLE_ID}
        secret-id: ${VAULT_SECRET_ID}
      kv:
        enabled: true
        backend: secret
        default-context: account-service

  config:
    import: vault://

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    url: /openapi.yaml
    oauth:
      client-id: ${ACCOUNT_SERVICE_SWAGGER_CLIENT_ID}
      use-pkce-with-authorization-code-grant: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

app:
  bik: ${BIK}
